-- Migration script to add issue mapping and embedding columns to sentiment_data table
-- This script should be run on your Railway PostgreSQL database

-- Add issue classification columns to sentiment_data table
ALTER TABLE sentiment_data
  ADD COLUMN IF NOT EXISTS issue_label TEXT,
  ADD COLUMN IF NOT EXISTS issue_slug TEXT,
  ADD COLUMN IF NOT EXISTS issue_confidence DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS issue_keywords JSONB,
  ADD COLUMN IF NOT EXISTS ministry_hint VARCHAR(50);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_sentiment_data_issue_slug ON sentiment_data (issue_slug);
CREATE INDEX IF NOT EXISTS idx_sentiment_data_ministry_hint ON sentiment_data (ministry_hint);
CREATE INDEX IF NOT EXISTS idx_sentiment_data_issue_confidence ON sentiment_data (issue_confidence);
CREATE INDEX IF NOT EXISTS idx_sentiment_data_user_platform_date ON sentiment_data (user_id, platform, published_at);

-- Create sentiment_embeddings table (Railway compatible - using JSONB instead of pgvector)
CREATE TABLE IF NOT EXISTS sentiment_embeddings (
  entry_id INT PRIMARY KEY REFERENCES sentiment_data(entry_id) ON DELETE CASCADE,
  embedding JSONB NOT NULL, -- Store as [0.1, 0.2, 0.3, ...] array (Railway compatible)
  embedding_model VARCHAR(50) DEFAULT 'text-embedding-3-small',
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes for embeddings table
CREATE INDEX IF NOT EXISTS idx_sentiment_embeddings_entry_id ON sentiment_embeddings (entry_id);
CREATE INDEX IF NOT EXISTS idx_sentiment_embeddings_model ON sentiment_embeddings (embedding_model);
CREATE INDEX IF NOT EXISTS idx_sentiment_embeddings_created_at ON sentiment_embeddings (created_at);

-- Add comments for documentation
COMMENT ON COLUMN sentiment_data.issue_label IS 'Human-readable issue label generated by AI';
COMMENT ON COLUMN sentiment_data.issue_slug IS 'URL-friendly identifier for issue grouping';
COMMENT ON COLUMN sentiment_data.issue_confidence IS 'Confidence score for issue classification (0.0 to 1.0)';
COMMENT ON COLUMN sentiment_data.issue_keywords IS 'Array of keywords extracted from content (JSONB)';
COMMENT ON COLUMN sentiment_data.ministry_hint IS 'Ministry or department this content relates to';

COMMENT ON TABLE sentiment_embeddings IS 'OpenAI embeddings for semantic similarity search (Railway compatible)';
COMMENT ON COLUMN sentiment_embeddings.embedding IS 'OpenAI text-embedding-3-small vector (1536 dimensions) stored as JSONB array';
COMMENT ON COLUMN sentiment_embeddings.embedding_model IS 'Model used to generate the embedding';

-- Verify the changes
SELECT 
  column_name, 
  data_type, 
  is_nullable,
  column_default
FROM information_schema.columns 
WHERE table_name = 'sentiment_data' 
  AND column_name IN ('issue_label', 'issue_slug', 'issue_confidence', 'issue_keywords', 'ministry_hint')
ORDER BY column_name;

-- Check if embeddings table was created
SELECT 
  table_name,
  column_name,
  data_type
FROM information_schema.columns 
WHERE table_name = 'sentiment_embeddings'
ORDER BY ordinal_position;

-- Show table sizes
SELECT 
  schemaname,
  tablename,
  attname,
  n_distinct,
  correlation
FROM pg_stats 
WHERE tablename IN ('sentiment_data', 'sentiment_embeddings')
ORDER BY tablename, attname;
